# snkV3 erhält keinen Zugriff beim Anlegen von output in readme Znih. da stimmt mehr nicht. Update gelöscht. WFoff

name: Generate GitHub Contribution Snake

on:
  schedule: 
    - cron: "0 0 * * *"  # Jeden Tag um Mitternacht
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # GitHub-Snake generieren
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output: output/github-snake.svg
          output_dark: output/github-snake-dark.svg?palette=github-dark

      # Änderungen committen und pushen
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Updated GitHub Contribution Snake"
          git push