name: Update Visitor Counter

on:
  schedule:
    - cron: "0 0 * * *" # Täglich um Mitternacht
  workflow_dispatch:

jobs:
  update-counter:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Nur Schreibrechte fürs Repository

    steps:
      # Repository auschecken
      - name: Check out the repository
        uses: actions/checkout@v2

      # GitHub-API-Daten abrufen
      - name: Fetch Visitor Data
        id: api_step
        env:
          API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -s -H "Authorization: Bearer $API_TOKEN" https://api.github.com/repos/Znih/Znih/traffic/views)
          
          # Überprüfen, ob die Antwort syntaktisch korrekt ist
          if echo "$RESPONSE" | jq empty > /dev/null 2>&1; then
            echo "API response valid."
          else
            echo "Ungültige API-Antwort! Beende Workflow."
            exit 1
          fi

          COUNT=$(echo "$RESPONSE" | jq '.count // 0') # Standardwert 0
          UNIQUES=$(echo "$RESPONSE" | jq '.uniques // 0')
          
          echo "count=$COUNT" >> $GITHUB_ENV
          echo "uniques=$UNIQUES" >> $GITHUB_ENV

          

      # Update README-Datei
      - name: Update README
        run: |
          sed -i "s/<!--visitor-counter-->.*$/<!--visitor-counter--> Besucher: ${{ env.count }}/" README.md
          sed -i "s/<!--visitor-uniques-->.*$/<!--visitor-uniques--> ${{ env.uniques }}/" README.md

      # Änderungen committen und pushen
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Aktualisiere Besucherzähler"
          git push
